#!/bin/bash

NAME=fastapi-app
USER={USERNAME}
GROUP={USERNAME}
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
BIND=unix:/run/user/{USERNAME}/gunicorn.sock
LOG_LEVEL=error

cd /home/{USERNAME}

exec gunicorn main:app \
    --name $NAME \
    --workers $WORKERS \
    --worker-class $WORKER_CLASS \
    --user=$USER \
    --group=$GROUP \
    --bind=$BIND \
    --log-level=$LOG_LEVEL \
    --log-file=-
