name: Multi platform / version testing
on: push

jobs:
  build:
    name: just test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,]
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrage core dependencies
        run: sudo python -m pip install --upgrade pip setuptools wheel

      - name: Run test
        run: sudo just test
